services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.production
    container_name: flick-server
    restart: unless-stopped
    env_file: .env
    networks:
      - flick-network
      - proxy

networks:
  flick-network:
    name: flick-network
    external: true
  proxy:
    name: proxy
    external: true
