FROM node:24-alpine
WORKDIR /app
COPY --chown=node:node package*.json ./
RUN chown node:node /app
USER node
RUN npm ci --omit=dev --ignore-scripts
COPY --chown=node:node . .
CMD ["node", "src/server.js"]