FROM node:24-alpine
WORKDIR /app
COPY --chown=node:node package*.json ./
RUN chown node:node /app
USER node
ENV NODE_ENV=production
RUN npm ci --omit=dev --ignore-scripts
COPY --chown=node:node . .

# Copy and setup entrypoint
COPY --chown=node:node entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]