FROM node:24-alpine
WORKDIR /app
COPY --chown=node:node package*.json ./
RUN chown node:node /app
USER node
ENV NODE_ENV=production
RUN npm ci --omit=dev --ignore-scripts
COPY --chown=node:node . .

# Make entrypoint executable
RUN chmod +x ./entrypoint.sh

ENTRYPOINT ["./entrypoint.sh"]